### ISSUE TITLE
Node UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by squealteam6** [balena-os/jetson-flash#74]
I am trying to flash a Jetson-nano using a workflow that was fine up until a few days ago. I'm getting the following error.

```
$$$@######:~/git/jetson-flash$ sudo ./bin/cmd.js -f ~/images/balena-image-jetson-nano-emmc.balenaos-img -m jetson-nano-emmc
Consistency check done for /tmp/24139/Linux_for_Tegra
Saved in /tmp/24139
Successfully generated hash
Checking resin cache
Cache image check done
Extracting partition LNX from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition DTB from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition RP1 from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition BMP from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition resin-boot from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition resin-rootA from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition resin-rootB from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition resin-state from /tmp/24139/resin/img to /tmp/24139/resin
Extracting partition resin-data from /tmp/24139/resin/img to /tmp/24139/resin
Data partition size in bytes: 212860928
Successfully generated hash
(node:24139) UnhandledPromiseRejectionWarning: Error: Cannot copy 'p3542-0000+p3448-0003-qspi-sd.conf' to a subdirectory of itself, 'p3542-0000+p3448-0003-qspi-sd.conf'.
    at /home/luke/git/jetson-flash/node_modules/fs-extra/lib/copy/copy.js:210:21
    at FSReqCallback.oncomplete (fs.js:156:23)
(node:24139) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24139) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by squealteam6** [comment]
Seems related to this [issue](https://github.com/balena-os/jetson-flash/issues/55)

**Comment by squealteam6** [comment]
removing "Linux_for_tegra" from the tmp directory solved the issue
